# Load environment variables from var.env
env_file:
  - ./var.env

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:80 # Point to Nginx
    depends_on:
      - nginx

  backend:
    build: ./backend
    deploy:
      replicas: 2
    expose:
      - "${PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./var.env
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
      - es01
      - es02
      - es03
      - redis-master
      - redis-slave-1
      - redis-slave-2
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api_gateway.conf:/etc/nginx/api_gateway.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Replica Set
  mongodb1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - mongodb_data1:/data/db
      - ./mongodb.conf:/etc/mongod.conf
    ulimits:
      memlock: -1
    networks:
      - app-network

  mongodb2:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - mongodb_data2:/data/db
      - ./mongodb.conf:/etc/mongod.conf
    ulimits:
      memlock: -1
    networks:
      - app-network

  mongodb3:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all"]
    environment:
      - GLIBC_TUNABLES=glibc.pthread.rseq=0
    volumes:
      - mongodb_data3:/data/db
      - ./mongodb.conf:/etc/mongod.conf
    ulimits:
      memlock: -1
    networks:
      - app-network

  # MongoDB setup script
  mongo-setup:
    image: mongo:latest
    depends_on:
      - mongodb1
      - mongodb2
      - mongodb3
    volumes:
      - ./scripts:/scripts
    command: ["bash", "/scripts/setup-replica.sh"]
    networks:
      - app-network

  # Elasticsearch Cluster
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data02:/usr/share/elasticsearch/data
    networks:
      - app-network

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data03:/usr/share/elasticsearch/data
    networks:
      - app-network

  # Scheduler service
  scheduler:
    build: ./scheduler
    environment:
      - API_URL=http://nginx/api/movies/fetch
    depends_on:
      - nginx
    networks:
      - app-network

  # Redis Master
  redis-master:
    image: redis:7.2
    command: redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_master_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

  # Redis Slave 1
  redis-slave-1:
    image: redis:7.2
    command: redis-server --slaveof redis-master ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    depends_on:
      - redis-master
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

  # Redis Slave 2
  redis-slave-2:
    image: redis:7.2
    command: redis-server --slaveof redis-master ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    depends_on:
      - redis-master
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

volumes:
  mongodb_data1:
  mongodb_data2:
  mongodb_data3:
  es_data01:
  es_data02:
  es_data03:
  nginx_logs:
  redis_master_data:

networks:
  app-network:
    driver: bridge